### ISSUE TITLE
A notice is always coming back after being closed

### ISSUE THREAD

**Issue by pawlshepherd** [gouarfig/board-notices#1]
Having issues with 0.5.3 - I'm told that it's not setting the cookie properly, which is why I can't get notices to stay closed. 
Can provide link if you wish.

**Comment by gouarfig** [comment]
Yes please, or maybe a screenshot of the error?
I need to remember how this work, I haven't worked on it for a while :)

**Comment by pawlshepherd** [comment]
URL is https://www.thewarpstorm.com/
There is a guest notice, but I can provide an account if you would rather. Notices close, but reopen upon page load.

**Comment by gouarfig** [comment]
It works fine for me.
I closed the "work in progress" notice in red background, and I'm not getting it back so far.

Now I can get it back if I clear my cookies.
Do you have some kind of browser extension that prevents setting some cookies?

**Comment by pawlshepherd** [comment]
Sorry, that's from the board announcements ext, forgot to disable it. 
![Screenshot_20200409-115531](https://user-images.githubusercontent.com/16684223/78888221-16b72200-7a59-11ea-82e3-d604fa33ef18.png)
![Screenshot_20200409-115540](https://user-images.githubusercontent.com/16684223/78888234-1cad0300-7a59-11ea-92c0-95cd6cd1a755.png)
Do you not see a test notice?

**Comment by gouarfig** [comment]
Yes, same behaviour.

I saw the "test" notice and managed to close it. It didn't come back until I cleared my cookies.
I'm using Firefox if that makes any difference

**Comment by pawlshepherd** [comment]
I've tried again, and have found that as a guest notices will close. Would you try one last thing to make sure it's not an issue in my end?
**[ credential deleted ]**
Should give you this notice. 
![Screenshot_20200409-121956](https://user-images.githubusercontent.com/16684223/78889939-985c7f00-7a5c-11ea-861d-4b0c7bef1eba.png)
![Screenshot_20200409-122010](https://user-images.githubusercontent.com/16684223/78889943-9abed900-7a5c-11ea-822b-94276dd46084.png)
Only one rule set. No notices will stay closed once logged in.

**Comment by gouarfig** [comment]
The notice always come back indeed.

Which version of phpBB are you using?

**Comment by pawlshepherd** [comment]
Glad I'm not going mad! 
3.2.8

**Comment by pawlshepherd** [comment]
It's been suggested to me that this might possibly be the cause, thought I would pass it on. =]
https://github.com/phpbb/phpbb/pull/5703

**Comment by gouarfig** [comment]
I don't think it's related.
I use cookies for guests, but for registered users it's written in the database: Otherwise you would have to close it on every browser you use (phone, tablet, computer, etc.)
I'm more thinking about an installation issue.

I can't really test it right now though: I need to rebuild my development evironment on my new machine first.

**Comment by pawlshepherd** [comment]
If you would like I would be happy to remove the files and reinstall from a fresh download?

**Comment by gouarfig** [comment]
Yes please, can you uninstall it completely (via the admin pages) and reinstall it fresh?
See if that fixes the issue first

**Comment by gouarfig** [comment]
Wait, there's no need for it, I found the defect.

It's only in the "User has not posted for" rule.

I'll make a new release with a fix

**Comment by pawlshepherd** [comment]
It might be worth checking at least one other, as I have the same issue with the "Number of visible posts equals or more than" rule. Sorry!
